options {
    listen-on port 53 { 127.0.0.1; 192.168.194.135; };
    directory     "/var/named";
    allow-query     { any; };
    recursion yes;
    dnssec-enable no;
    dnssec-validation no;
};

zone "ouyang.com" IN {
    type master;
    file "ouyang.com.zone";
};

zone "zhou.com" IN {
    type master;
    file "zhou.com.zone";
};
