server {
    listen 80;
    server_name www.ouyang.com;
    root /data/web/ouyang;
    index index.html;
}

server {
    listen 80;
    server_name www.zhou.com;
    root /data/web/zhou;
    index index.html;
}
